<a href="https://colab.research.google.com/github/SteAmarante/python-data-science/blob/main/aula_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#⭐ Introdução ao NumPy Arrays e Operações Básicas ⭐

##Vetores, matrizes e tensores

In [ ]:
#importando biblioteca
import numpy as np

###Vetores

Um vetor é uma matriz unidimensional de números. Em termos
simples, um vetor é uma seta que representa uma quantidade que
tem magnitude e direção.

In [ ]:
#cria um vetor com numpy
meu_vetor = np.array([10, 11, 13, 11, 14, 15])
print(meu_vetor)
print("\n")
print(meu_vetor.shape)

[10 11 13 11 14 15]


(6,)


###Matrizes

Uma matriz é uma estrutura bidimensional de números. É como uma tabela ou
grade com linhas e colunas.

Cada elemento em uma matriz é identificado por dois índices em vez de apenas
um. Se uma matriz tem uma altura de m e uma largura de n, então dizemos que
ela é uma matriz (m x n), onde m representa suas linhas e n representa suas
colunas. No exemplo abaixo, usamos duas listas de 3 elementos cada para criar
uma matriz 2 x 3 com NumPy.

In [ ]:
# cria uma matriz 2 x 3
minha_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(minha_matrix.shape) # resultado: (2, 3)
print("\n")
print(minha_matrix)

(2, 3)


[[1 2 3]
 [4 5 6]]


###Tensores

Os tensores podem ser simplesmente entendidos como uma matriz n-dimensional com n maior que 2. A notação matemática dos tensores é semelhante à das matrizes. Por exemplo, para armazenar dados de uma imagem colorida, podemos usar um tensor com 3 dimensões: a largura da imagem, sua altura e o número de canais de cores.

In [ ]:
import numpy as np

#cria um tensor 3, 2, 3
meu_tensor = np.array([
    [
      [0,1,0], [1,0,1]
    ],
    [
      [0,1,0], [1,0,1]
    ],
    [
      [0,1,0], [1,0,1]
    ]
])
print(meu_tensor.shape)
print("\n")
print(meu_tensor)

(3, 2, 3)


[[[0 1 0]
  [1 0 1]]

 [[0 1 0]
  [1 0 1]]

 [[0 1 0]
  [1 0 1]]]


##Manipulando os meus Arrays

###Reshaping
Isso converterá sua matriz unidimensional em uma matriz bidimensional com 2 linhas e 3 colunas.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


In [ ]:
new_arr = arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


###Cópia
A nova matriz apenas faz referência à matriz antiga na memória do sistema. Eles contêm os mesmos elementos e não são independentes um do outro.

Você pode copiar os elementos de um array NumPy para outra usando o método copy(). Você deve observar que o uso do operador de atribuição ‘=’ cria uma cópia superficial.

Ao usar a cópia copy(), você cria um novo array NumPy que contém os mesmos dados que a antiga e é independente dela.

In [ ]:
#Creating a shallow copy of a NumPy array
a = np.array([9, 6, 12, 16, 20])
b = a
b[0] = 19

print(a) #Output:[19, 6, 12, 16, 20]
print(b) #Output:[19, 6, 12, 16, 20]

[19  6 12 16 20]
[19  6 12 16 20]


###Concatenação

Ocasionalmente, pode ser necessário mesclar dois array em um único. No NumPy, você pode usar a função concatenate() para unir matrizes ao longo de um eixo existente:

Isso combina arr1 e arr2 em um único array. Lembre-se de que os array que estão sendo concatenadas devem ter o mesmo formato, exceto ao longo do eixo especificado.

In [55]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.concatenate((arr1, arr2))
result = result.reshape(2, 3)
# result = result.conjugate(arr1)
print(result)

[[1 2 3]
 [4 5 6]]


###Splitting
Splitting é o oposto da concatenação. Você pode dividir um array em sub-arrays menores usando a função split()

Isso divide a matriz em 3 sub- arrays de tamanho igual. Certifique-se de que o número de divisões que você especificar possa dividir uniformemente o tamanho do array ao longo do eixo fornecido.

In [ ]:
a = np.array([3, 5, 6, 9, 1, 0])
print(a)

[3 5 6 9 1 0]


In [ ]:
a, b, c = np.split(a, 3)
print(a, b, c)

[3 5] [6 9] [1 0]


###Adição/Remoção de elementos

É possível adicionar ou remover elementos em um array NumPy usando as funções append() e delete(). Você pode usar a primeira para acrescentar valores ao final do array, enquanto a segunda exclui o elemento em um índice especificado.

In [46]:
arr = np.array([1, 2, 3])

arr = np.append (arr, [4, 5, 6])
print(arr)
print("\n")
arr = np.delete(arr, 0)
print(arr)

[1 2 3 4 5 6]


[2 3 4 5 6]


###Slicing

Você também pode fatiar matrizes NumPy para extrair ou visualizar uma seção
dos dados da mesma forma que faria com listas ou conjuntos do Python. Vamos dar uma olhada em um exemplo abaixo:

In [58]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr2 = np.array([(1, 2, 3,6,0),(4,5,6,11,13)])

# To return the first 3 elements of arr1
print(arr1[0:3]) #Output: [1, 2, 3]

# To return the second row in arr2
b = arr2[1, : ].copy() #Output: [4, 5, 6, 11, 13]

[1 2 3]


##Exercícios Individuais – Manipulação de Arrays NumPy

### Exercício 1
Crie um array NumPy com valores de 0 a 11, faça um reshape deste array para uma matriz 3x4. Utilizando indexação, imprima:

*   Toda a segunda linha.
*   O valor localizado na terceira linha, quarta coluna.

In [68]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
new_a = a.reshape(3, 4)
print(new_a)
print("\nToda a segunda linha: ")
print(new_a[1])
print("\nO valor localizado na terceira linha, quarta coluna: ")
print(new_a[2,3]) #quando usa ":" faz fatiamento, e a "," traz linhas e coluna

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Toda a segunda linha: 
[4 5 6 7]

O valor localizado na terceira linha, quarta coluna: 
11


###Exercício 2
Crie dois arrays 1D NumPy com valores [1, 2, 3] e [4, 5, 6] e concatene-os formando um único array. Após isso,
faça slicing para obter apenas os elementos [2, 3, 4, 5].

In [72]:
um_arr = ([1, 2, 3])
dois_arr = ([4, 5, 6])
novo_arr = np.concatenate((um_arr, dois_arr))
print(novo_arr)
print("\n")
print(novo_arr[1:5])

[1 2 3 4 5 6]


[2 3 4 5]


###Exercício 3

Crie um array original com valores [10, 20, 30, 40, 50]. Faça uma cópia deste array. Remova o elemento 30 da cópia sem alterar o original. Imprima os dois arrays para mostrar que o original permanece inalterado.

In [79]:
og_arr = ([10, 20, 30, 40, 50])
print(og_arr)
print("\n")
nova_og = og_arr.copy()
print(nova_og)
print("\n")
nova_og = np.delete(nova_og, 2)
print(nova_og)

[10, 20, 30, 40, 50]


[10, 20, 30, 40, 50]


[10 20 40 50]


###Exercício 4

Crie um array com valores [100, 200, 300, 400, 500, 600], divida-o (split) esse array em dois arrays separados, cada um com três elementos. No segundo array resultante, adicione o valor 700 ao final. Imprima ambos arrays finais.

In [80]:
print("Array original ----\n")
arr = np.array([100, 200, 300, 400, 500, 600])
print(arr)

print("\nArrays split ----\n")
arr1, arr2 = np.split(arr, 2)
print(arr1, '\n')
print(arr2)

print("\nArrays split com alteração no segundo ----\n")
print(arr1, '\n')
arr2 = np.append(arr2, 700)
print(arr2)

[100 200 300 400 500 600]
[100 200 300] 

[400 500 600]
[100 200 300] 

[400 500 600]


##Funções/Operações para os Arrays

###Operações aritiméticas

O NumPy oferece várias operações matemáticas em matrizes que as tornam simples
e eficientes para trabalhar. matemática de matrizes matemática de vetores. Algumas das operações são:

- Adição: numpy.add(x1, x2)
- Subtração: numpy.subtract(x1, x2)
- Multiplicação: numpy.multiply(x1, x2)
- Divisão: numpy.divide(x1, x2)
- Módulo: numpy.mod(x1, x2)
- Potência: numpy.power(x1, x2)
- Raiz quadrada: numpy.sqrt(x)

Observação: Ao usar essas operações, as duas matrizes devem ter o mesmo formato. Caso contrário, você encontrará erros.

In [81]:
a = np.array([8, 4, 9, 2])
b = np.array([2, 4, 3, 2.5])
print(a,b)

[8 4 9 2] [2.  4.  3.  2.5]


In [82]:
c = np.add(a, b) #Alternatively c = atb
print(c)

[10.   8.  12.   4.5]


In [83]:
c = np.multiply (a,b) #Alternatively c = a*b
print(c)

[16. 16. 27.  5.]


In [84]:
c =np.sqrt(a)
print(c)

[2.82842712 2.         3.         1.41421356]


###Funções de agregação
O NumPy fornece várias funções de agregação que permitem realizar
operações em matrizes, como somar todos os seus elementos, encontrar o
valor mínimo ou máximo e muito mais:

- sum: np.sum(your_array) - Calcula a soma de todos os
elementos da matriz.
- min: np.min(your_array) - Encontra o elemento mínimo da
matriz.
- max: np.max(your_array) - Localiza o elemento máximo da
matriz.
- mean: np.mean(your_array) - Calcula a média dos valores na
matriz.
- median: np.median(your_array) - Encontre a mediana dos
valores na matriz.
- std: np.std(your_array) – Devolve o desvio padrão

In [85]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [86]:
print(np.sum(a))

45


In [87]:
print(np.max(a))

9


In [88]:
print(np.mean(a))

4.5


###Broadcasting

Broadcasting é um recurso poderoso do NumPy que permite realizar operações em matrizes com diferentes formas e tamanhos. Ele funciona expandindo automaticamente as dimensões da matriz menor para corresponder à matriz maior, facilitando a realização de operações elementares.

In [91]:
A = np.array([1, 2, 3])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

C = A + B
print(C)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


##Exercícios Individuais – Funções/Operações para os Arrays

###Exercício 1

Crie dois arrays NumPy: A = [10, 20, 30, 40, 50] e B = [1, 2, 3, 4, 5]. Realize as seguintes operações entre eles:

- Soma
- Subtração
- Multiplicação
- Divisão

Imprima claramente cada resultado.

In [94]:
p_arr = ([10, 20, 30, 40, 50])
s_arr = ([1, 2, 3, 4, 5])

calculo = np.add(p_arr, s_arr)
print(f"A soma é: {calculo}")

calculo = np.subtract(p_arr, s_arr)
print(f"\nA subtração é: {calculo}")

calculo = np.multiply(p_arr, s_arr)
print(f"\nA multiplicação é: {calculo}")

calculo = np.divide(p_arr, s_arr)
print(f"\nA divisão é: {calculo}")

A soma é: [11 22 33 44 55]

A subtração é: [ 9 18 27 36 45]

A multiplicação é: [ 10  40  90 160 250]

A divisão é: [10. 10. 10. 10. 10.]


###Exercício 2

Crie um array NumPy com os seguintes valores: [12, 15, 20, 25, 30, 35, 40]. Utilize funções NumPy para calcular:

- Soma total
- Média
- Desvio padrão
- Máximo e mínimo

Imprima cada resultado com clareza.

In [113]:
valores_arr = ([12, 15, 20, 25, 30, 35, 40])

print("Soma total: ")
print(np.sum(valores_arr))

print("\nMédia: ")
print(np.mean(valores_arr))

print("\nDesvio padrão: ")
print(np.std(valores_arr))

print("\nMáximo e mínimo: ")
print(np.max(valores_arr), np.min(valores_arr))

Soma total: 
177

Média: 
25.285714285714285

Desvio padrão: 
9.587406706035724

Máximo e mínimo: 
40 12


### Exercício 3

Crie uma matriz NumPy (2x3): [[1, 2, 3], [4, 5, 6]] e então adicione o vetor
[10, 20, 30] a cada linha da matriz usando broadcasting, multiplique a matriz
resultante pelo escalar 2 e Imprima a matriz inicial, após soma e após
multiplicação.

In [110]:
m_arr = np.array([[1, 2, 3], [4, 5, 6]])
v = np.array([10, 20, 30])

adc = m_arr + v

escalar = adc * 2

print("Matriz original: ")
print(m_arr)

print("\nAdição do vetor: ")
print(v)

print("\nSoma da matriz origial: ")
print(adc)
print("\nMultiplicação da Matriz origial: ")
print(escalar)


Matriz original: 
[[1 2 3]
 [4 5 6]]

Adição do vetor: 
[10 20 30]

Soma da matriz origial: 
[[11 22 33]
 [14 25 36]]

Multiplicação da Matriz origial: 
[[22 44 66]
 [28 50 72]]


### Exercício 4

Crie um array de dimensões (3,1) com valores [10, 20, 30] e então crie
outro array unidimensional com valores [1, 2, 3]. Utilize broadcasting para
multiplicar esses arrays gerando uma matriz (3x3)por fim imprima claramente
os arrays originais e a matriz final.

In [126]:
dim_arr = np.array([[10], [20], [30]])
uni_di = np.array([1, 2, 3])

matriz_n = dim_arr * uni_di

print("\nArray dimensional (3,1): ")
print(dim_arr)
print("\nArray unidimensional: ")
print(uni_di)

print("\nMultiplicação: ")
print(matriz_n)




Array dimensional (3,1): 
[[10]
 [20]
 [30]]

Array unidimensional: 
[1 2 3]

Multiplicação: 
[[10 20 30]
 [20 40 60]
 [30 60 90]]
